<Project Sdk="Microsoft.NET.Sdk">
	
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>CS8618;CS0649</NoWarn>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <Version>1.2.0</Version>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageReference Include="Eto.Forms" Version="2.11.0" />
    <PackageReference Include="Eto.Serialization.Xaml" Version="2.11.0" />
  </ItemGroup>
  
  <ItemGroup>
    <ProjectReference Include="../../MatroskaLib\MatroskaLib\MatroskaLib.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="logo.ico">
    </EmbeddedResource>
  </ItemGroup>
  
</Project>