<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-Windows</TargetFramework>
    <RootNamespace>MkvDefaultTrackChanger.WinForms</RootNamespace>
    <ApplicationIcon>..\MkvDefaultTrackChanger\logo.ico</ApplicationIcon>
    
    <!-- Single File Publishing Options -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>
  
  <ItemGroup>
    <ProjectReference Include="..\MkvDefaultTrackChanger\MkvDefaultTrackChanger.csproj" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Eto.Platform.Windows" Version="2.10.2" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="..\MkvDefaultTrackChanger\logo.ico">
      <Link>logo.ico</Link>
    </None>
  </ItemGroup>
</Project>
